In [187]:
import string

import numpy as np
import  pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ammar\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [188]:
df = pd.read_csv('spam.csv', encoding='utf-16')

In [189]:
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [190]:
df = df.drop(['Unnamed: 2','Unnamed: 3','Unnamed: 4'],axis=1)

In [191]:
df['v1'].value_counts()

v1
ham     4825
spam     747
Name: count, dtype: int64

In [192]:
df.shape

(5572, 2)

In [193]:
df = df.rename(columns={'v1': 'label', 'v2': 'message'})

In [194]:
df.isna().sum()

label      0
message    0
dtype: int64

In [195]:
df.duplicated().sum()

np.int64(403)

In [196]:
df.drop_duplicates(inplace=True)

In [197]:
from  sklearn.preprocessing import OneHotEncoder

In [198]:
encoder = OneHotEncoder()

In [199]:
df = pd.get_dummies(df,columns=['label'],drop_first=True)

In [200]:
spamMessages = df[df['label_spam']==1]

In [201]:
spamMessages

                                                message  label_spam
2     Free entry in 2 a wkly comp to win FA Cup fina...        True
5     FreeMsg Hey there darling it's been 3 week's n...        True
8     WINNER!! As a valued network customer you have...        True
9     Had your mobile 11 months or more? U R entitle...        True
11    SIX chances to win CASH! From 100 to 20,000 po...        True
...                                                 ...         ...
5537  Want explicit SEX in 30 secs? Ring 02073162414...        True
5540  ASKED 3MOBILE IF 0870 CHATLINES INCLU IN FREE ...        True
5547  Had your contract mobile 11 Mnths? Latest Moto...        True
5566  REMINDER FROM O2: To get 2.50 pounds free call...        True
5567  This is the 2nd time we have tried 2 contact u...        True

[653 rows x 2 columns]

In [202]:
word_counts = df['message'].str.lower().str.split().explode().value_counts()

In [203]:
word_counts

message
i                  2095
to                 2055
you                1832
a                  1281
the                1223
                   ...
yeh.                  1
kane                  1
he.                   1
shud                  1
pshew...missing       1
Name: count, Length: 13494, dtype: int64

In [204]:
import string
from nltk.corpus import stopwords

# Load stopwords once
STOP_WORDS = set(stopwords.words("english"))

def preprocess_text(text):
    """
    Text preprocessing pipeline:
    1. Lowercase
    2. Remove punctuation
    3. Tokenize
    4. Remove stopwords
    5. Rejoin words
    """

    # Convert to lowercase
    text = text.lower()

    # Remove punctuation
    translator = str.maketrans('', '', string.punctuation)
    text = text.translate(translator)

    # Tokenize
    words = text.split()

    # Remove stopwords
    words = [word for word in words if word not in STOP_WORDS]

    # Join back into a sentence
    return " ".join(words)

In [205]:
df['message'] = df['message'].apply(preprocess_text)

In [206]:
df['message']

0       go jurong point crazy available bugis n great ...
1                                 ok lar joking wif u oni
2       free entry 2 wkly comp win fa cup final tkts 2...
3                     u dun say early hor u c already say
4             nah dont think goes usf lives around though
                              ...
5567    2nd time tried 2 contact u u �750 pound prize ...
5568                          � b going esplanade fr home
5569                          pity mood soany suggestions
5570    guy bitching acted like id interested buying s...
5571                                       rofl true name
Name: message, Length: 5169, dtype: object

In [212]:
spamMessages['message']

                                              message  label_spam
2   Free entry in 2 a wkly comp to win FA Cup fina...        True
5   FreeMsg Hey there darling it's been 3 week's n...        True
8   WINNER!! As a valued network customer you have...        True
9   Had your mobile 11 months or more? U R entitle...        True
11  SIX chances to win CASH! From 100 to 20,000 po...        True

In [213]:
spamMessages['message'].str.lower().str.split().explode().value_counts()

message
to         591
a          328
call       298
your       241
you        226
          ...
o            1
bailiff      1
shit.        1
giv          1
bill.        1
Name: count, Length: 3732, dtype: int64